package main

import (
	"bytes"
	"errors"
	"strconv"
	"strings"
	"testing"

	"github.com/macdylan/SMFix/fix"
)

var validInput = `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; first_layer_bed_temperature = 60, 65
; nozzle_diameter = 0.4, 0.4
; layer_height = 0.2
; total_layer_number = 100
; filament_type = PLA,ABS
; filament used [mm] = 5000.00, 3000.00
; filament used [g] = 12.50, 7.50
; estimated printing time (normal mode) = 1h 30m 0s
; retract_length = 1.2, 1.5
; max_print_speed = 100
T0
G1 X1.234 Y2.345 E0.01234 F1500
G4 S0
G4 P100
` + strings.Repeat("G1 X1 Y1 E0.001 F1500\n", 30)

func TestReadGcodes(t *testing.T) {
	gcodes, err := readGcodes(strings.NewReader(validInput))
	if err != nil {
		t.Fatal(err)
	}
	// empty lines skipped, "G4 S0" skipped, everything else kept
	for _, line := range []string{"G4 S0", ""} {
		for _, g := range gcodes {
			if g.String() == line {
				t.Errorf("line %q should have been skipped", line)
			}
		}
	}
	found := false
	for _, g := range gcodes {
		if g.String() == "G4 P100" {
			found = true
		}
	}
	if !found {
		t.Error("G4 P100 should have been kept")
	}
}

func TestReadGcodes_ErrIsFixed(t *testing.T) {
	_, err := readGcodes(strings.NewReader(fix.Mark + "\nG0 X0\n"))
	if !errors.Is(err, fix.ErrIsFixed) {
		t.Errorf("got %v, want ErrIsFixed", err)
	}
}

// lines above the bufio default 64 KB limit must not abort the scan
func TestReadGcodes_LongLine(t *testing.T) {
	long := strings.Repeat(";", maxScanTokenSize/2) // 512 KB comment
	input := "G0 X0\n" + long + "\nG0 X1\n"
	gcodes, err := readGcodes(strings.NewReader(input))
	if err != nil {
		t.Fatalf("long line should not fail: %v", err)
	}
	if len(gcodes) != 3 {
		t.Errorf("got %d blocks, want 3", len(gcodes))
	}
	if gcodes[1].Comment() != long {
		t.Error("long comment content mismatch")
	}
}

func TestProcess(t *testing.T) {
	var out bytes.Buffer
	if err := process(strings.NewReader(validInput), &out); err != nil {
		t.Fatal(err)
	}
	result := out.String()

	if strings.ContainsRune(result, 0) {
		t.Error("output contains NUL byte")
	}
	if !strings.HasPrefix(result, fix.Mark) {
		t.Errorf("output should start with the smfix mark: %q", result[:40])
	}
	if !strings.Contains(result, ";machine: Snapmaker 2.0 A350\n") {
		t.Error("missing machine header")
	}

	// the declared line count must match the actual output
	lines := strings.Count(result, "\n")
	declared := -1
	for _, line := range strings.Split(result, "\n") {
		if strings.HasPrefix(line, ";file_total_lines:") {
			v, err := strconv.Atoi(strings.TrimSpace(line[len(";file_total_lines:"):]))
			if err != nil {
				t.Fatal(err)
			}
			declared = v
		}
	}
	if declared < 0 {
		t.Fatal("file_total_lines header not found")
	}
	if declared != lines {
		t.Errorf("file_total_lines = %d, actual lines = %d", declared, lines)
	}
}

func TestProcess_ErrIsFixed(t *testing.T) {
	var out bytes.Buffer
	err := process(strings.NewReader(fix.Mark+"\nG0 X0\n"), &out)
	if !errors.Is(err, fix.ErrIsFixed) {
		t.Errorf("got %v, want ErrIsFixed", err)
	}
}

func BenchmarkProcess(b *testing.B) {
	// ~1 MB synthetic input
	input := validInput + strings.Repeat("G1 X1.234 Y2.345 E0.01234 F1500\n", 15000)
	b.SetBytes(int64(len(input)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		var out bytes.Buffer
		out.Grow(len(input) * 2)
		if err := process(strings.NewReader(input), &out); err != nil {
			b.Fatal(err)
		}
	}
}
