package main

import (
	"bytes"
	"errors"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/macdylan/SMFix/fix"
)

var validInput = `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; first_layer_bed_temperature = 60, 65
; nozzle_diameter = 0.4, 0.4
; layer_height = 0.2
; total_layer_number = 100
; filament_type = PLA,ABS
; filament used [mm] = 5000.00, 3000.00
; filament used [g] = 12.50, 7.50
; estimated printing time (normal mode) = 1h 30m 0s
; retract_length = 1.2, 1.5
; max_print_speed = 100
T0
G1 X1.234 Y2.345 E0.01234 F1500
G4 S0
G4 P100
` + strings.Repeat("G1 X1 Y1 E0.001 F1500\n", 30)

func TestReadGcodes(t *testing.T) {
	gcodes, err := readGcodes(strings.NewReader(validInput))
	if err != nil {
		t.Fatal(err)
	}
	// empty lines skipped, "G4 S0" skipped, everything else kept
	for _, line := range []string{"G4 S0", ""} {
		for _, g := range gcodes {
			if g.String() == line {
				t.Errorf("line %q should have been skipped", line)
			}
		}
	}
	found := false
	for _, g := range gcodes {
		if g.String() == "G4 P100" {
			found = true
		}
	}
	if !found {
		t.Error("G4 P100 should have been kept")
	}
}

func TestReadGcodes_ErrIsFixed(t *testing.T) {
	_, err := readGcodes(strings.NewReader(fix.Mark + "\nG0 X0\n"))
	if !errors.Is(err, fix.ErrIsFixed) {
		t.Errorf("got %v, want ErrIsFixed", err)
	}
}

// lines above the bufio default 64 KB limit must not abort the scan
func TestReadGcodes_LongLine(t *testing.T) {
	long := strings.Repeat(";", maxScanTokenSize/2) // 512 KB comment
	input := "G0 X0\n" + long + "\nG0 X1\n"
	gcodes, err := readGcodes(strings.NewReader(input))
	if err != nil {
		t.Fatalf("long line should not fail: %v", err)
	}
	if len(gcodes) != 3 {
		t.Errorf("got %d blocks, want 3", len(gcodes))
	}
	if gcodes[1].Comment() != long {
		t.Error("long comment content mismatch")
	}
}

func TestProcess(t *testing.T) {
	var out bytes.Buffer
	if err := process(strings.NewReader(validInput), &out); err != nil {
		t.Fatal(err)
	}
	result := out.String()

	if strings.ContainsRune(result, 0) {
		t.Error("output contains NUL byte")
	}
	if !strings.HasPrefix(result, fix.Mark) {
		t.Errorf("output should start with the smfix mark: %q", result[:40])
	}
	if !strings.Contains(result, ";machine: Snapmaker 2.0 A350\n") {
		t.Error("missing machine header")
	}

	// the declared line count must match the actual output
	lines := strings.Count(result, "\n")
	declared := -1
	for _, line := range strings.Split(result, "\n") {
		if strings.HasPrefix(line, ";file_total_lines:") {
			v, err := strconv.Atoi(strings.TrimSpace(line[len(";file_total_lines:"):]))
			if err != nil {
				t.Fatal(err)
			}
			declared = v
		}
	}
	if declared < 0 {
		t.Fatal("file_total_lines header not found")
	}
	if declared != lines {
		t.Errorf("file_total_lines = %d, actual lines = %d", declared, lines)
	}
}

func TestProcess_ErrIsFixed(t *testing.T) {
	var out bytes.Buffer
	err := process(strings.NewReader(fix.Mark+"\nG0 X0\n"), &out)
	if !errors.Is(err, fix.ErrIsFixed) {
		t.Errorf("got %v, want ErrIsFixed", err)
	}
}

var u1Input = `; generated by Snapmaker Orca 2.2.4 on 2026-01-01
; printer_model = Snapmaker U1
; printer_settings_id = Snapmaker U1 (0.4 nozzle)
; first_layer_temperature = 220, 220, 220, 220
; filament_type = PLA;PETG;ABS;ASA
; filament used [mm] = 100.00, 200.00, 300.00, 400.00
SET_PRINT_AUTO_BED_LEVELING ENABLE=1
PRINT_START
M104 S0 T0 A0
M104 S0 T1 A0
M104 S0 T2 A0
M104 S0 T3 A0
M106 P2 S0
M109 S220 T3
T0
T3

G1 X1.234 Y2.345 E0.01234  F1500
G4 S0
` + strings.Repeat("G1 X1 Y1 E0.001 F1500\n", 20)

// U1 files must pass through byte-identical (raw copy after the mark
// line): no header, no tool folding, no shutoff rewrites, no parser
// normalization (blank lines, G4 S0 and spacing all preserved).
func TestProcess_U1Passthrough(t *testing.T) {
	var out bytes.Buffer
	if err := process(strings.NewReader(u1Input), &out); err != nil {
		t.Fatal(err)
	}
	result := out.String()

	if !strings.HasPrefix(result, fix.Mark+"\n") {
		t.Error("output should start with the smfix mark")
	}
	body := result[len(fix.Mark)+1:]
	if body != u1Input {
		t.Errorf("U1 file was modified:\n--- got ---\n%s\n--- want ---\n%s", body, u1Input)
	}
	if strings.Contains(result, ";Header Start") || strings.Contains(result, ";file_total_lines") {
		t.Error("SM2 header must not be injected into U1 files")
	}
}

// real U1 slices (trimmed: start gcode + config block) must survive
// byte-identical through both slicers' output formats
func TestProcess_U1RealFiles(t *testing.T) {
	for _, name := range []string{
		"fix/testdata/u1_snapmaker_orca.gcode",
		"fix/testdata/u1_orcaslicer.gcode",
	} {
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile(name)
			if err != nil {
				t.Fatal(err)
			}
			var out bytes.Buffer
			if err := process(bytes.NewReader(raw), &out); err != nil {
				t.Fatal(err)
			}
			got := out.String()
			if !strings.HasPrefix(got, fix.Mark+"\n") {
				t.Error("output should start with the smfix mark")
			}
			if body := got[len(fix.Mark)+1:]; body != string(raw) {
				t.Errorf("%s: passthrough is not byte-identical", name)
			}
			if strings.Contains(got, ";Header Start") {
				t.Error("SM2 header must not be injected into U1 files")
			}
		})
	}
}

func TestUsageText(t *testing.T) {
	s := usageText("vTest", "/usr/local/bin/smfix")
	for _, want := range []string{
		"Usage:",
		"smfix [flags] <input.gcode>",
		"smfix vTest -",
		"/usr/local/bin/smfix",
		"overwritten in place",
		"Snapmaker U1 files",
		"PrusaSlicer integration",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("usage text missing %q", want)
		}
	}
	if strings.Contains(s, "%!") {
		t.Errorf("format artifact in usage text")
	}
}

func BenchmarkProcess(b *testing.B) {
	// ~1 MB synthetic input
	input := validInput + strings.Repeat("G1 X1.234 Y2.345 E0.01234 F1500\n", 15000)
	b.SetBytes(int64(len(input)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		var out bytes.Buffer
		out.Grow(len(input) * 2)
		if err := process(strings.NewReader(input), &out); err != nil {
			b.Fatal(err)
		}
	}
}
