package fix

import (
	"strconv"
	"strings"
	"testing"
)

// benchFixture builds a synthetic dual-extruder gcode that resembles real
// PrusaSlicer/OrcaSlicer output: settings block, M73 progress lines,
// tool changes with M104/M109 temperature commands and move commands.
func benchFixture(lines int) []*GcodeBlock {
	var sb strings.Builder
	sb.WriteString("; generated by PrusaSlicer 2.7.0\n")
	sb.WriteString("; printer_model = A350\n")
	sb.WriteString("; first_layer_temperature = 215, 220\n")
	sb.WriteString("; first_layer_bed_temperature = 60, 65\n")
	sb.WriteString("; nozzle_diameter = 0.4, 0.4\n")
	sb.WriteString("; layer_height = 0.2\n")
	sb.WriteString("; total_layer_number = 1000\n")
	sb.WriteString("; filament_type = PLA,ABS\n")
	sb.WriteString("; filament used [mm] = 5000.00, 3000.00\n")
	sb.WriteString("; filament used [g] = 12.50, 7.50\n")
	sb.WriteString("; estimated printing time (normal mode) = 1h 30m 0s\n")
	sb.WriteString("; retract_length = 1.2, 1.5\n")
	sb.WriteString("; max_print_speed = 100\n")

	moves := lines - 16
	for i := 0; i < moves; i++ {
		switch i % 10 {
		case 0:
			sb.WriteString("M73 P" + strconv.Itoa(i%100) + " R" + strconv.Itoa(3600-i%3600) + "\n")
		case 5:
			tool := i / 100 % 2
			sb.WriteString("T" + strconv.Itoa(tool) + "\n")
			sb.WriteString("M104 S" + strconv.Itoa(200+tool*10) + " T" + strconv.Itoa(tool) + "\n")
		case 7:
			sb.WriteString("M104 S0 T" + strconv.Itoa(i/100%2) + " ; cooldown\n")
		default:
			sb.WriteString("G1 X1.234 Y2.345 E0.01234 F1500\n")
		}
	}
	return _parseGcodes(sb.String())
}

func BenchmarkParseParams(b *testing.B) {
	gcodes := benchFixture(20000)
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := ParseParams(gcodes); err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkGcodeFixShutoffB(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		b.StopTimer()
		gcodes := benchFixture(20000)
		b.StartTimer()
		GcodeFixShutoff(gcodes)
	}
}

func BenchmarkGcodeReplaceToolNumB(b *testing.B) {
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		b.StopTimer()
		gcodes := benchFixture(20000)
		b.StartTimer()
		GcodeReplaceToolNum(gcodes)
	}
}
