package fix

import (
	"bytes"
	"errors"
	"reflect"
	"strings"
	"testing"
)

func split_(s string) (gcodes [][]byte) {
	b := bytes.NewBufferString(s)
	for {
		line, err := b.ReadBytes('\n')
		if err != nil {
			break
		}
		gcodes = append(gcodes, line[0:len(line)-1])
	}
	return gcodes
}

func TestConvertThumbnail(t *testing.T) {
	gcodes := split_(`; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 60%
; top_solid_layers = 6
; generated by PrusaSlicer 2.4.2+arm64 on 2022-05-12 at 06:33:34 UTC
G0
G1

;
; thumbnail begin 16x16 536
; aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
; bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
; thumbnail end
;
G0
G1
;
; thumbnail begin 220x124 6528
; xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
; yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
; zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
; thumbnail end
;
;

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm

`)

	comp := []byte("data:image/png;base64,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz")
	r := convertThumbnail(gcodes)
	if 0 != bytes.Compare(r, comp) {
		t.Error(r, comp)
	}
}

func TestConvertEstimatedTime(t *testing.T) {
	gcodes := " 2s "
	if r := convertEstimatedTime(gcodes); 2 != r {
		t.Error("2s /", r)
	}
	gcodes = "1m 2s "
	if r := convertEstimatedTime(gcodes); 60+2 != r {
		t.Error("1m 2s /", r)
	}
	gcodes = " 1h  2s"
	if r := convertEstimatedTime(gcodes); 3600+2 != r {
		t.Error("1h 2s /", r)
	}
	gcodes = " 2d 1m  2s"
	if r := convertEstimatedTime(gcodes); 2*86400+1*60+2 != r {
		t.Error("2d 1m 2s /", r)
	}
}

func TestSplit(t *testing.T) {
	s := "a"
	r := split(s)
	if len(r) != 2 {
		t.Error("len is not 2, but:", len(r))
	}
	if r[0] != "a" {
		t.Error("index 0 value is not a, but:", r[0])
	}
	if r[1] != "" {
		t.Error("index 1 value is not empty, but:", r[1])
	}

	s = "xxxx, yy yy "
	r = split(s)
	if len(r) != 2 {
		t.Error("len is not 2, but:", len(r))
	}
	if r[0] != "xxxx" {
		t.Error("index 0 value is not xxxx, but:", r[0])
	}
	if r[1] != "yy yy" {
		t.Error("index 1 value is not yy yy, but:", r[1])
	}

	s = "ABS,PETG,PLA"
	r = split(s)
	if len(r) != 3 {
		t.Error("len is not 2, but:", len(r))
	}
	if r[0] != "ABS" {
		t.Error("index 0 value is not xxxx, but:", r[0])
	}
	if r[1] != "PETG" {
		t.Error("index 1 value is not yy yy, but:", r[1])
	}
}

func TestSplitFloat(t *testing.T) {
	s := "0.2"
	r := splitFloat(s)
	if len(r) != 2 {
		t.Error("len is not 2, but:", len(r))
	}
	if r[0] != 0.2 {
		t.Error("index 0 value is not 0.2, but:", r[0])
	}
	if r[1] != 0 {
		t.Error("index 1 value is not 0, but:", r[1])
	}

	s = "0.4, 0.689123"
	r = splitFloat(s)
	if len(r) != 2 {
		t.Error("len is not 2, but:", len(r))
	}
	if r[0] != 0.4 {
		t.Error("index 0 value is not 0.4, but:", r[0])
	}
	if r[1] != 0.689123 {
		t.Error("index 1 value is not 0.689123, but:", r[1])
	}

	s = "nil,123"
	r = splitFloat(s)
	if len(r) != 2 {
		t.Error("len is not 2, but:", len(r))
	}
	if r[0] != 0 {
		t.Error("index 0 value is not 0, but:", r[0])
	}
	if r[1] != 123 {
		t.Error("index 1 value is not 123, but:", r[1])
	}

	s = "nil,789,123"
	r = splitFloat(s)
	if len(r) != 3 {
		t.Error("len is not 3, but:", len(r))
	}
	if r[0] != 0 {
		t.Error("index 0 value is not 0, but:", r[0])
	}
	if r[1] != 789 {
		t.Error("index 1 value is not 789, but:", r[1])
	}
}

func _parseGcodes(s string) []*GcodeBlock {
	gcodes := strings.Split(s, "\n")
	r := make([]*GcodeBlock, 0, len(gcodes))
	for _, g := range gcodes {
		block, err := ParseGcodeBlock(g)
		if err != nil {
			// panic(err)
			continue
		}
		r = append(r, block)
	}
	return r
}

func TestGcodeShutoff(t *testing.T) {
	gcode := `
T0 ; initial tool
M104 S200 T1
T1
M104 S200 T1
T0
M104 S100 T1 ; (remove useless)

M104 S200 T0
M104 S200 T1 ; (remove useless)
M109 S200 T1 ; (remove useless)

M104 S0 T0
M104 S0 T1 ; (keep)
M73 P100 R0 ; end
	`
	gcodes := _parseGcodes(gcode)

	comp := `
T0 ; initial tool
M104 S200 T1
T1
M104 S200 T1
T0
M104 S0 T1 ; (Fixed: Shutoff T1)
;(Fixed: T1 has been shutted off: M104 S100 T1)

M104 S200 T0
;(Fixed: T1 has been shutted off: M104 S200 T1)
;(Fixed: T1 has been shutted off: M109 S200 T1)

M104 S0 T0
M104 S0 T1 ; (keep)
M73 P100 R0 ; end
		`
	comp_gcodes := _parseGcodes(comp)

	result := GcodeFixShutoff(gcodes)
	if (reflect.DeepEqual(result, comp_gcodes)) != true {
		results := make([]string, 0, len(result)+len(comp_gcodes)+1)
		for _, g := range result {
			results = append(results, g.String())
		}
		results = append(results, "==========>")
		for _, g := range comp_gcodes {
			results = append(results, g.String())
		}
		t.Error(strings.Join(results, "\n"))
	}
}

func TestGcodePreheat(t *testing.T) {
	gcode := `
M73 P0 R60
M109 T0 S200
M109 T1 S210 ; prepare

; deep freeze {{
; standby but heat-up after 5 mins, need to be freeze >>
M104 S154 ;standby T0
M73 P4 R55
; pre-heat (long) here >>
M73 P4 R54
M73 P4 R53
M73 P4 R52
M73 P4 R51
M109 T0 S200 ; wait T0
;}} end deep freeze

; pre-heat short {{
M104 S154 ;standby T1
M73 P5 R43
; standby but heat-up in 3 mins, pre heat (short) here >>
M73 P5 R42
M73 P5 R41
M109 T1 S221 C3 W1 ;wait T1
; }} end pre-heat short

; remove cooldown {{
M104 S178 ;standby T0 (remove)
T1
M109 T1 S555 C3 W1 ;wait T1
M73 P6 R21
T0
M109 T0 S255 C3 W1 ;wait T0
; }} end remove cooldown

M104 S555 T1 ; <- already requested
M109 T1 S100 ; <- diff temp, keep this
M109 S100 T1; <- already stabilized

M73 P8 R25
T0
M104 S225 ; heat
M104 S220 ; added by slicer
T1
M104 S154 T0 ;standby T0
M73 P11 R29
M109 T1 S220 ;wait T1

; nothing to do {{
T0
M104 S244
M109 S244
T1
M109 S111 C3 W1 ; wait T1
T0
M109 S244 ; wait T0

M109 T1 S255 C3 W1 ;wait T1
M104 T0 S0
M104 T1 S0
G28 ; home
M73 P100 R0 ; end
; }}
	`
	gcodes := _parseGcodes(gcode)

	comp := `
M73 P0 R60
M109 T0 S200
M109 T1 S210 ; prepare

; deep freeze {{
; standby but heat-up after 5 mins, need to be freeze >>
M104 T0 S110 ;(Fixed: deep freeze instead of: M104 S154)
M73 P4 R55
; pre-heat (long) here >>
M104 T0 S200 ;(Fixed: pre-heat long)
M73 P4 R54
M73 P4 R53
M73 P4 R52
M73 P4 R51
M109 T0 S200 ; wait T0
;}} end deep freeze

; pre-heat short {{
M104 S154 ;standby T1
M73 P5 R43
; standby but heat-up in 3 mins, pre heat (short) here >>
M104 T1 S221 ;(Fixed: pre-heat short)
M73 P5 R42
M73 P5 R41
M109 T1 S221 C3 W1 ;wait T1
; }} end pre-heat short

; remove cooldown {{
;(Fixed: remove cooldown: M104 S178)
T1
M109 T1 S555 C3 W1 ;wait T1
M73 P6 R21
T0
M109 T0 S255 C3 W1 ;wait T0
; }} end remove cooldown

;(Fixed: already requested temp: M104 S555 T1)
M109 T1 S100 ; <- diff temp, keep this
;(Fixed: already stabilized temp: M109 S100 T1)

M73 P8 R25
T0
M104 S225 ; heat
M104 S220 ; added by slicer
T1
;(Fixed: remove cooldown: M104 S154 T0)
M73 P11 R29
M109 T1 S220 ;wait T1

; nothing to do {{
T0
M104 S244
M109 S244
T1
M109 S111 C3 W1 ; wait T1
T0
M109 S244 ; wait T0

M109 T1 S255 C3 W1 ;wait T1
M104 T0 S0
M104 T1 S0
G28 ; home
M73 P100 R0 ; end
; }}
		`
	comp_gcodes := _parseGcodes(comp)

	result := GcodeFixPreheat(gcodes)
	if (reflect.DeepEqual(result, comp_gcodes)) != true {
		results := make([]string, 0, len(result)+len(comp_gcodes)+1)
		for _, g := range result {
			results = append(results, g.String())
		}
		results = append(results, "==========>")
		for _, g := range comp_gcodes {
			results = append(results, g.String())
		}
		t.Error(strings.Join(results, "\n"))
	}
}

/*
	func TestGcodeTrimLines(t *testing.T) {
		gcode := `
		G0 X0

G0 X1

	G0 X3
	;
	;
	; setting_1 = value1, value2
	;


	G4 S0
	G4 P100

G4 S0 ; comments

# G0 X4

G0 X5
`

	gcodes := _parseGcodes(gcode)

	comp := `

G0 X0
G0 X1

# G0 X3

; setting_1 = value1, value2

# G4 P100

# G0 X4

G0 X5
`

		comp_gcodes := _parseGcodes(comp)

		result := GcodeTrimLines(gcodes)
		if (reflect.DeepEqual(result, comp_gcodes)) != true {
			results := make([]string, 0, len(result)+len(comp_gcodes)+1)
			for _, g := range result {
				results = append(results, g.String())
			}
			results = append(results, "==========>")
			for _, g := range comp_gcodes {
				results = append(results, g.String())
			}
			t.Error(strings.Join(results, "\n"))
		}
	}
*/

/*
func TestGcodeReinforceTower(t *testing.T) {
	gcode := `
G1  X176.579  E4.2970 F1584
;Z:0.3
; CP TOOLCHANGE WIPE
G1  X176.579  E1.2970 F1584
G1  Y31.500  E0.1900
G1  X142.329  E1.3017 F1800
G1 F19200
G92 E0
; CP TOOLCHANGE END
;Z:0.4
G1  X176.579  E1.2970 F1584
; CP TOOLCHANGE WIPE
M73 R80
G1  X176.579  E2.2970 F1584
G1  Y31.500  E0.1900
G1  X176.579  E4.3017 F2198
G1  Y36.500  E0.1900
G1  X176.579  E4.3017 F2198
G1 F19200
G92 E0
; CP TOOLCHANGE END
G1  X176.579  E1.2970 F1584
`

	gcodes := _parseGcodes(gcode)

	comp := `
G1  X176.579  E4.2970 F1584
;Z:0.3
; CP TOOLCHANGE WIPE
G1  X176.579  E1.2970 F1584
G1  Y31.500  E0.1900
G1  X142.329  E1.3017 F1800
G1 F19200
G92 E0
; CP TOOLCHANGE END
;Z:0.4
G1  X176.579  E1.2970 F1584
; CP TOOLCHANGE WIPE
M73 R80
G1 E1.0336499 F1584 ;(Fixed: reinforce tower)
G1  X176.579  E2.2970 F1584
G1  Y31.500  E0.1900
G1 E1.0336499 F1584 ;(Fixed: reinforce tower)
G1  X176.579  E4.3017 F2198
G1  Y36.500  E0.1900
G1 E1.0336499 F1584 ;(Fixed: reinforce tower)
G1  X176.579  E4.3017 F2198
G1 F19200
G92 E0
; CP TOOLCHANGE END
G1  X176.579  E1.2970 F1584
`

	comp_gcodes := _parseGcodes(comp)

	result := GcodeReinforceTower(gcodes)
	if (reflect.DeepEqual(result, comp_gcodes)) != true {
		results := make([]string, 0, len(result)+len(comp_gcodes)+1)
		for _, g := range result {
			results = append(results, g.String())
		}
		results = append(results, "==========>")
		for _, g := range comp_gcodes {
			results = append(results, g.String())
		}
		t.Error(strings.Join(results, "\n"))
	}
}
*/

func TestGcodeReplaceToolNum(t *testing.T) {
	t.Run("replace gcode", func(t *testing.T) {
		cases := []struct {
			raw  string
			want string
		}{
			{"T0 ; tool T0", "T0  ; tool T0"},
			{"T1 ; tool T1", "T1  ; tool T1"},
			{"T3 ; tool T3", "T1  ; tool T3"},
			{"T63 ; tool T63", "T1  ; tool T63"},
			{"M104 S255", "M104 S255"},
			{"M109 S255 C2 W1", "M109 S255 C2 W1"},
			{"M104 T0 S200", "M104 T0 S200"},
			{"M104 T1 S200", "M104 T1 S200"},
			{"M104 T3 S200", "M104 T1 S200"},
			{"M104 T63 S200", "M104 T1 S200"},
			{"M106 S255", "M106 S255"},
			{"M107", "M107"},
			{"M106 P0 S200", "M106 P0 S200"},
			{"M106 P62 S200", "M106 P0 S200"},
			{"M107 P0 ; fan off", "M107 P0 ; fan off"},
			{"M107 P62 ; fan off", "M107 P0 ; fan off"},
			{"M301 E3 T0", "M301 E1 T0"},
			{"M303 E4 T1", "M303 E0 T1"},
			{"M108 T33 ; fake cmd", "M108 T33 ; fake cmd"},
			{"G1 T33", "G1 T33"},
		}

		for _, tc := range cases {
			g, err := ParseGcodeBlock(tc.raw)
			if err != nil {
				t.Fatal(err)
			}
			gcodes := []*GcodeBlock{g}
			result := GcodeReplaceToolNum(gcodes)
			if result[0].String() != tc.want {
				t.Errorf("Got %q, want %q", g, tc.want)
			}
		}
	})

	comp := func(gcodes []*GcodeBlock, want []*GcodeBlock) {
		got := GcodeReplaceToolNum(gcodes)
		if (reflect.DeepEqual(got, want)) != true {
			results := make([]string, 0, len(got)+len(want)+1)
			for _, g := range got {
				results = append(results, g.String())
			}
			results = append(results, "==========>")
			for _, g := range want {
				results = append(results, g.String())
			}
			t.Error(strings.Join(results, "\n"))
		}
	}
	t.Run("replace comment 1", func(t *testing.T) {
		gcodes := _parseGcodes(`
T0
T1
; filament used [mm] = 5989.21, 4703.92
; filament used [cm3] = 14.41, 11.31
; filament used [g] = 17.86, 14.03
; filament cost = 0, 0, 0, 1.07, 0.84; total filament used [g] = 31.89
		`)
		want := _parseGcodes(`
T0
T1
; filament used [mm] = 5989.21,4703.92
; filament used [cm3] = 14.41,11.31
; filament used [g] = 17.86,14.03
; filament cost = 0, 0, 0, 1.07, 0.84; total filament used [g] = 31.89
		`)
		comp(gcodes, want)
	})

	t.Run("replace comment 2", func(t *testing.T) {
		gcodes := _parseGcodes(`
T1
; filament used [mm] = 0, 4703.92
; filament used [cm3] = 0, 11.31
; filament used [g] = 0, 14.03
		`)
		want := _parseGcodes(`
T1
; filament used [mm] = 0,4703.92
; filament used [cm3] = 0,11.31
; filament used [g] = 0,14.03
		`)
		comp(gcodes, want)
	})

	t.Run("replace comment 3", func(t *testing.T) {
		gcodes := _parseGcodes(`
T3
T2
; filament used [mm] = 0, 0, 5989.21, 4703.92
; filament used [cm3] = 0, 0, 14.41, 11.31
; filament used [g] = 0, 0, 17.86, 14.03
		`)
		want := _parseGcodes(`
T1
T0
; filament used [mm] = 5989.21,4703.92
; filament used [cm3] = 14.41,11.31
; filament used [g] = 17.86,14.03
		`)
		comp(gcodes, want)
	})

	t.Run("replace comment 4", func(t *testing.T) {
		gcodes := _parseGcodes(`
T2
T1
; filament used [mm] = 0, 9, 5989.21, 4703.92
; filament_type = PLA;ABS; PETG; ASA
; first_layer_bed_temperature = 70
; hot_plate_temp_initial_layer = 55, 95, 70,100
		`)
		want := _parseGcodes(`
T0
T1
; filament used [mm] = 5989.21,9
; filament_type = PETG;ABS
; first_layer_bed_temperature = 70
; hot_plate_temp_initial_layer = 70,95
		`)
		comp(gcodes, want)
	})
}

func TestGcode(t *testing.T) {
	{ // NewGcode
		cases := map[string]struct {
			word  byte
			addr  string
			valid bool
		}{
			"*0X": {'*', "0X", false},
			"y":   {'Y', "", false},
			"0":   {'0', "", false},

			"X*": {'X', "*", true},
			"B":  {'B', "", true},
			"B0": {'B', "0", true},

			"G0":   {'G', "0", true},
			"E-3":  {'E', "-3", true},
			"G.1":  {'G', ".1", true},
			"G-.1": {'G', "-.1", true},

			"E.00001":       {'E', ".00001", true},
			"E-.00001":      {'E', "-.00001", true},
			"E.000001":      {'E', ".000001", true},
			"X-9999.000001": {'X', "-9999.000001", true},
		}
		for raw, tc := range cases {
			t.Run(raw, func(t *testing.T) {
				g, err := NewGcode(tc.word, tc.addr)
				if tc.valid {
					if err != nil {
						t.Errorf("unexpected error: %v", err)
					} else {
						if g.String() != raw {
							t.Errorf("(%s) but want(%s)", g, raw)
						}
					}
				} else {
					if err == nil && g.String() == raw {
						t.Errorf("unexpected success: (%v) want (%s)", g, raw)
					}
				}
			})
		}
	}

	{ // ParseGcode
		_, err := ParseGcode("")
		if err == nil || err.Error() != ErrEmptyString.Error() {
			t.Errorf("unexpected error: %v", err)
		}
	}

	{ // SetAddr
		cases := []struct {
			want   string
			origin *Gcode
			new    any
			err    error
		}{
			{"E0.00000", &Gcode{'E', "6", 1 + uint16(len("6"))}, 0.000001, nil}, // 0.000001 < 0.00001
			{"E0.00001", &Gcode{'E', "6", 1 + uint16(len("6"))}, 0.00001, nil},
			{"E3", &Gcode{'E', "", 1 + uint16(len(""))}, 3, nil},
			{"E4", &Gcode{'E', "", 1 + uint16(len(""))}, int32(4), nil},
			{"E5", &Gcode{'E', "", 1 + uint16(len(""))}, int64(5), nil},
			{"E6", &Gcode{'E', "", 1 + uint16(len(""))}, uint(6), nil},
			{"E7", &Gcode{'E', "", 1 + uint16(len(""))}, uint32(7), nil},
			{"E8", &Gcode{'E', "", 1 + uint16(len(""))}, uint64(8), nil},
			{"E9.10000", &Gcode{'E', "", 1 + uint16(len(""))}, float32(9.1), nil}, // E.5f
			{"E9.20000", &Gcode{'E', "", 1 + uint16(len(""))}, float64(9.2), nil},
			{"R", &Gcode{'R', "999", 1 + uint16(len("999"))}, nil, nil},
			{"Z", &Gcode{'Z', "999", 1 + uint16(len("999"))}, false, errors.New("unsupported addr type bool")},
			{"S", &Gcode{'S', "999", 1 + uint16(len("999"))}, errors.ErrUnsupported, errors.New("unsupported addr type *errors.errorString")},
			{"X0.001", &Gcode{'X', "", 1 + uint16(len(""))}, 0.001, nil},
			{"X-0.001", &Gcode{'X', "", 1 + uint16(len(""))}, -0.001, nil},
			{"E1.23457", &Gcode{'E', "", 1 + uint16(len(""))}, 1.23456789, nil},        // E.5f
			{"E-1.23457", &Gcode{'E', "", 1 + uint16(len(""))}, -1.23456789, nil},      // E.5f
			{"E-1.23456789", &Gcode{'E', "", 1 + uint16(len(""))}, "-1.23456789", nil}, // string
			{"X0.000", &Gcode{'X', "6", 1 + uint16(len("6"))}, 0.0001, nil},            // 0.0001 < 0.001
			{"X1.235", &Gcode{'X', "", 1 + uint16(len(""))}, 1.23456789, nil},          // .3f
		}

		for _, c := range cases {
			t.Run(c.want, func(t *testing.T) {
				if err := c.origin.SetAddr(c.new); err != nil && c.err != nil {
					if err.Error() != c.err.Error() {
						t.Errorf("unexpected error: %v", err)
					}
					return
				}
				if c.origin.String() != c.want {
					t.Errorf("(%s) but want(%s)", c.origin, c.want)
				}
			})
		}
	}

	{ // AddrAs
		var origin *Gcode

		var str string
		origin = &Gcode{'X', "6", 1 + uint16(len("6"))}
		origin.AddrAs(&str)
		if str != "6" {
			t.Errorf("unexpected addr: %v", str)
		}

		var i int
		origin.AddrAs(&i)
		if i != 6 {
			t.Errorf("unexpected addr: %v", i)
		}

		var i32 int32
		origin.AddrAs(&i32)
		if i32 != 6 {
			t.Errorf("unexpected addr: %v", i32)
		}

		var f32 float32
		origin.AddrAs(&f32)
		if f32 != 6 {
			t.Errorf("unexpected addr: %v", f32)
		}

		origin = &Gcode{'X', ".000001", 1 + uint16(len(".000001"))}
		origin.AddrAs(&f32)
		if f32 != 0.000001 {
			t.Errorf("unexpected addr: %v", f32)
		}

		var f64 float64
		if err := origin.AddrAs(&f64); err == nil || err.Error() != "unsupported addr type as *float64" {
			t.Errorf("unexpected error: %v", err)
		}
	}

}

func TestParseGcodeBlock(t *testing.T) {
	{ // validate all funcs
		s := " M1 X1.23 Y2.456 Z.3 E-.004 F500000 ; a comment T63 "
		g, err := ParseGcodeBlock(s)
		if err != nil {
			t.Errorf("unexpected error: %v", err)
		}

		if g.String() != strings.TrimSpace(s) {
			t.Errorf("unexpected string: %v", g.String())
		}
		if !g.Is("M1") {
			t.Errorf("unexpected command: %v", g.Cmd().String())
		}
		if !g.HasParam('X') {
			t.Errorf("expected param X but not: %v", g.Cmd().String())
		}
		if g.HasParam('M') {
			t.Errorf("unexpected param M: %v", g.Cmd().String())
		}
		var e float32
		if err := g.GetParam('E', &e); err == nil && e != -0.004 {
			t.Errorf("expected -0.004 but not: %v", e)
		} else if err != nil {
			t.Errorf("unexpected error: %v", err)
		}
		if new := g.Copy(); new.String() != g.String() {
			t.Errorf("unexpected copy: %v", new.String())
		}
		if g.Comment() != "; a comment T63" {
			t.Errorf("unexpected comment: %v", g.Comment())
		}
		if tool, err := g.GetToolNum(); tool != 63 || err != nil {
			t.Errorf("unexpected tool: %v, err: %s, comment: %s", tool, err, g.Comment())
		}
		g.SetComment("; another comment %d", 123)
		if g.Comment() != "; another comment 123" {
			t.Errorf("unexpected comment: %v", g.Comment())
		}
		g.AppendComment(", append %.3f", .456)
		comment := "; another comment 123, append 0.456"
		if g.Comment() != comment {
			t.Errorf("unexpected comment: %v", g.Comment())
		}
		if r := g.Format("%m"); r != comment {
			t.Errorf("unexpected comment: %v", r)
		}
		format := "this is a %c gcode"
		if r := g.Format(format); r != "this is a M1 gcode" {
			t.Errorf("unexpected format: %q", r)
		}
		if !g.InComment("0.456") {
			t.Errorf("expect 0.456 in comment but not: %v", g.Comment())
		}
	}
	{ // get tool num
		cases := map[string]int32{
			"M104 S154 ;standby T0":     0,
			"M104 S154 ; standby  T64;": 64,
			"M104 T0 S154 ;standby   T": 0,
			"M104 T0 S154 ; standby T9": 0,
			"M106 P3 S154":              3,
			"M106 T0 P4 S154":           4,
			"M107 T0 P5 S154":           5,
			"M303 T1 P2 E3 S154":        3,
			"T0":                        0,
			"T-1":                       -1,
			"T0;T1":                     0,
			"M0 T-1;T-3":                -1,
			";T1":                       1,
			// ";T-3":                      -3, // not support in comment
		}

		for s, want := range cases {
			g, err := ParseGcodeBlock(s)
			if err != nil {
				t.Errorf("unexpected error: %v", err)
			}
			if tool, err := g.GetToolNum(); tool != want || err != nil {
				t.Errorf("unexpected tool: %v, err: %s, %s", tool, err, g)
			}
		}
	}

	{
		// raw -> want
		cases := [][2]string{
			{" G0.1   X1.23 Y.456000 F500000 ", "G0.1 X1.23 Y.456000 F500000"},
			{"G0 X1.23 Y.456000 ; comment", "G0 X1.23 Y.456000 ; comment"},
			{" T64", "T64"},
			{"M900 K-.04", "M900 K-.04"},
			{"; config = value\nss ", "; config = value\nss"},
			{";; a comment ", ";; a comment"},
			{";", ";"},
			{"G1 123", "G1"},
			{"M220 R", "M220 R"},
			{"G28 X Y", "G28 X Y"},
			{"X Y Z", "X Y Z"},
			{"G28 N*", "G28 N*"},
			{"N**", "N**"},
			{"N;comm", "N  ;comm"}, // N as command, %p be replaced as a space
		}

		for _, c := range cases {
			result, err := ParseGcodeBlock(c[0])
			if err != nil {
				t.Errorf("unexpected error: %v (%s)", err, c[0])
				break
			}
			if result.String() != c[1] {
				t.Errorf("(%v) but want(%v)", result, c[1])
			}
		}
	}
}

func TestGcodeFixOrcaToolUnload(t *testing.T) {
	gcode := `
M104 S199
; LAYER_HEIGHT: 0.2
; FEATURE: Prime tower
; LINE_WIDTH: 0.5
;--------------------
; CP TOOLCHANGE START
; toolchange #2
; material : PETG -> PET
;--------------------
M220 B
M220 S100
; CP TOOLCHANGE UNLOAD
; LINE_WIDTH: 0.6
; LINE_WIDTH: 0.5
M104 S250 T0
M104 S278
M104 S255; T1
; Cooling park
G4 S0
G1 E-2 F2100
; CP TOOLCHANGE END
;------------------
M104 S299
`
	gcodes := _parseGcodes(gcode)

	comp := `
M104 S199
; LAYER_HEIGHT: 0.2
; FEATURE: Prime tower
; LINE_WIDTH: 0.5
;--------------------
; CP TOOLCHANGE START
; toolchange #2
; material : PETG -> PET
;--------------------
M220 B
M220 S100
; CP TOOLCHANGE UNLOAD
; LINE_WIDTH: 0.6
; LINE_WIDTH: 0.5
M104 S250 T0
;(Fixed: remove: M104 S278)
M104 S255; T1
; Cooling park
G4 S0
G1 E-2 F2100
; CP TOOLCHANGE END
;------------------
M104 S299
`
	comp_gcodes := _parseGcodes(comp)

	result := GcodeFixOrcaToolUnload(gcodes)
	if (reflect.DeepEqual(result, comp_gcodes)) != true {
		results := make([]string, 0, len(result)+len(comp_gcodes)+1)
		for _, g := range result {
			results = append(results, g.String())
		}
		results = append(results, "==========>")
		for _, g := range comp_gcodes {
			results = append(results, g.String())
		}
		t.Error(strings.Join(results, "\n"))
	}
}

func _padToLines(n int) string {
	var sb strings.Builder
	for i := 0; i < n; i++ {
		sb.WriteString("G0 X0 Y0\n")
	}
	return sb.String()
}

func _validPrusaSlicerGcode() string {
	return `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; bed_shape = 0x0,320x350
; first_layer_temperature = 215, 220
; first_layer_bed_temperature = 60, 65
; nozzle_diameter = 0.4, 0.4
; layer_height = 0.2
; total_layer_number = 150
; filament_type = PLA,ABS
; filament used [mm] = 5000, 3000
; filament used [g] = 12.5, 7.5
; estimated printing time (normal mode) = 1h 30m 0s
; retract_length = 1.2, 1.5
; retract_length_toolchange = 3.0, 3.5
; max_print_speed = 100
; min_x = 10
; min_y = 20
; min_z = 0.2
; max_x = 300
; max_y = 330
; max_z = 50.4
; printer_notes = Don't lose focus!
` + _padToLines(10)
}

func TestParseParams_ValidPrusaSlicer(t *testing.T) {
	gcodes := _parseGcodes(_validPrusaSlicerGcode())
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	p := Params
	if p.Model != ModelA350 {
		t.Errorf("Model: got %q, want %q", p.Model, ModelA350)
	}
	if p.Version != 0 {
		t.Errorf("Version: got %d, want 0", p.Version)
	}
	if p.LayerHeight != 0.2 {
		t.Errorf("LayerHeight: got %f, want 0.2", p.LayerHeight)
	}
	if p.TotalLayers != 150 {
		t.Errorf("TotalLayers: got %d, want 150", p.TotalLayers)
	}
	if p.NozzleTemperatures[0] != 215 || p.NozzleTemperatures[1] != 220 {
		t.Errorf("NozzleTemperatures: got %v, want [215, 220]", p.NozzleTemperatures)
	}
	if p.BedTemperatures[0] != 60 || p.BedTemperatures[1] != 65 {
		t.Errorf("BedTemperatures: got %v, want [60, 65]", p.BedTemperatures)
	}
	if p.NozzleDiameters[0] != 0.4 || p.NozzleDiameters[1] != 0.4 {
		t.Errorf("NozzleDiameters: got %v, want [0.4, 0.4]", p.NozzleDiameters)
	}
	if p.FilamentTypes[0] != "PLA" || p.FilamentTypes[1] != "ABS" {
		t.Errorf("FilamentTypes: got %v, want [PLA, ABS]", p.FilamentTypes)
	}
	if p.FilamentUsed[0] != 5000 || p.FilamentUsed[1] != 3000 {
		t.Errorf("FilamentUsed: got %v, want [5000, 3000]", p.FilamentUsed)
	}
	if p.FilamentUsedWeight[0] != 12.5 || p.FilamentUsedWeight[1] != 7.5 {
		t.Errorf("FilamentUsedWeight: got %v, want [12.5, 7.5]", p.FilamentUsedWeight)
	}
	if p.EstimatedTimeSec != 5400 {
		t.Errorf("EstimatedTimeSec: got %d, want 5400", p.EstimatedTimeSec)
	}
	if p.Retractions[0] != 1.2 || p.Retractions[1] != 1.5 {
		t.Errorf("Retractions: got %v, want [1.2, 1.5]", p.Retractions)
	}
	if p.SwitchRetraction[0] != 3.0 || p.SwitchRetraction[1] != 3.5 {
		t.Errorf("SwitchRetraction: got %v, want [3.0, 3.5]", p.SwitchRetraction)
	}
	if p.PrintSpeedSec != 100 {
		t.Errorf("PrintSpeedSec: got %f, want 100", p.PrintSpeedSec)
	}
	if p.MinX != 10 || p.MinY != 20 || p.MinZ != 0.2 {
		t.Errorf("Min: got (%f,%f,%f), want (10,20,0.2)", p.MinX, p.MinY, p.MinZ)
	}
	if p.MaxX != 300 || p.MaxY != 330 || p.MaxZ != 50.4 {
		t.Errorf("Max: got (%f,%f,%f), want (300,330,50.4)", p.MaxX, p.MaxY, p.MaxZ)
	}
	if !p.LeftExtruderUsed || !p.RightExtruderUsed {
		t.Errorf("ExtruderUsed: got (%v,%v), want (true,true)", p.LeftExtruderUsed, p.RightExtruderUsed)
	}
	if p.ToolHead != ToolheadDual {
		t.Errorf("ToolHead: got %q, want %q", p.ToolHead, ToolheadDual)
	}
	if p.PrintMode != PrintModeDefault {
		t.Errorf("PrintMode: got %q, want %q", p.PrintMode, PrintModeDefault)
	}
}

func TestParseParams_ValidBBS(t *testing.T) {
	gcode := `; generated by Bambu Studio 1.7.0
; printer_model = J1
; nozzle_temperature_initial_layer = 220, 230
; hot_plate_temp_initial_layer = 55, 60
; nozzle_diameter = 0.4, 0.4
; first_layer_height = 0.2
; total layers count = 200
; filament_type = PETG;ASA
; filament used [mm] = 4000, 2000
; filament used [g] = 10, 5
; estimated printing time (normal mode) = 2h 0m 0s
; filament_retraction_length = 1.0, 1.2
; retract_length = 0.5, 0.6
; retract_length_toolchange = 2.0, 2.5
; outer_wall_speed = 80
; min_x = 5
; min_y = 10
; min_z = 0.1
; max_x = 300
; max_y = 190
; max_z = 40
` + _padToLines(10)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	p := Params
	if p.Model != ModelJ1 {
		t.Errorf("Model: got %q, want %q", p.Model, ModelJ1)
	}
	if p.Version != 1 {
		t.Errorf("Version: got %d, want 1 (J1 forces v1)", p.Version)
	}
	if p.TotalLayers != 200 {
		t.Errorf("TotalLayers: got %d, want 200", p.TotalLayers)
	}
	if p.NozzleTemperatures[0] != 220 || p.NozzleTemperatures[1] != 230 {
		t.Errorf("NozzleTemperatures: got %v, want [220, 230]", p.NozzleTemperatures)
	}
	if p.BedTemperatures[0] != 55 || p.BedTemperatures[1] != 60 {
		t.Errorf("BedTemperatures: got %v, want [55, 60]", p.BedTemperatures)
	}
	if p.FilamentTypes[0] != "PETG" || p.FilamentTypes[1] != "ASA" {
		t.Errorf("FilamentTypes: got %v, want [PETG, ASA]", p.FilamentTypes)
	}
	if p.Retractions[0] != 1.0 || p.Retractions[1] != 1.2 {
		t.Errorf("Retractions: got %v, want [1.0, 1.2] (filament_retraction_length overrides retract_length)", p.Retractions)
	}
	if p.PrintSpeedSec != 80 {
		t.Errorf("PrintSpeedSec: got %f, want 80", p.PrintSpeedSec)
	}
}

func TestParseParams_ErrIsFixed(t *testing.T) {
	gcode := `; Postprocessed by smfix (https://github.com/macdylan/SMFix)
; generated by PrusaSlicer 2.7.0
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	err := ParseParams(gcodes)
	if err != ErrIsFixed {
		t.Errorf("got %v, want ErrIsFixed", err)
	}
}

func TestParseParams_ErrInvalidGcode_TooFewLines(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
G0 X0
G0 X1
`
	gcodes := _parseGcodes(gcode)
	err := ParseParams(gcodes)
	if err != ErrInvalidGcode {
		t.Errorf("got %v, want ErrInvalidGcode (too few lines)", err)
	}
}

func TestParseParams_ErrInvalidGcode_NoModel(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; first_layer_temperature = 215, 220
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	err := ParseParams(gcodes)
	if err != ErrInvalidGcode {
		t.Errorf("got %v, want ErrInvalidGcode (no model)", err)
	}
}

func TestParseParams_ErrInvalidGcode_NoTemperature(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; filament used [mm] = 5000, 3000
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	err := ParseParams(gcodes)
	if err != ErrInvalidGcode {
		t.Errorf("got %v, want ErrInvalidGcode (no temperature)", err)
	}
}

func TestParseParams_ModelFromBedShape(t *testing.T) {
	cases := []struct {
		bedShape string
		want     string
	}{
		{"0x0,160x160", ModelA150},
		{"0x0,230x250", ModelA250},
		{"0x0,320x350", ModelA350},
		{"0x0,400x400", ModelA400},
		{"0x0,312x200", ModelJ1},
		{"0x0,270x270", ModelU1},
	}

	for _, tc := range cases {
		t.Run(tc.want, func(t *testing.T) {
			gcode := `; generated by PrusaSlicer 2.7.0
; bed_shape = ` + tc.bedShape + `
; first_layer_temperature = 215, 220
` + _padToLines(25)

			gcodes := _parseGcodes(gcode)
			if err := ParseParams(gcodes); err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if Params.Model != tc.want {
				t.Errorf("Model: got %q, want %q (bed_shape=%q)", Params.Model, tc.want, tc.bedShape)
			}
		})
	}
}

func TestParseParams_ModelFromPrinterModel(t *testing.T) {
	cases := []struct {
		model string
		want  string
	}{
		{"SNAPMAKER A150", ModelA150},
		{"SNAPMAKER A250", ModelA250},
		{"SNAPMAKER A350", ModelA350},
		{"SNAPMAKER Artisan", ModelA400},
		{"SNAPMAKER J1", ModelJ1},
		{"SNAPMAKER U1", ModelU1},
	}

	for _, tc := range cases {
		t.Run(tc.want, func(t *testing.T) {
			gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = ` + tc.model + `
; first_layer_temperature = 215, 220
` + _padToLines(25)

			gcodes := _parseGcodes(gcode)
			if err := ParseParams(gcodes); err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if Params.Model != tc.want {
				t.Errorf("Model: got %q, want %q", Params.Model, tc.want)
			}
		})
	}
}

func TestParseParams_PrintModes(t *testing.T) {
	t.Run("Duplication", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; first_layer_temperature = 215, 220
M605 S2
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if Params.PrintMode != PrintModeDuplication {
			t.Errorf("PrintMode: got %q, want %q", Params.PrintMode, PrintModeDuplication)
		}
		if Params.Model != ModelJ1 {
			t.Errorf("Model: got %q, want %q (IDEX forces J1)", Params.Model, ModelJ1)
		}
		if Params.Version != 1 {
			t.Errorf("Version: got %d, want 1 (IDEX forces v1)", Params.Version)
		}
	})

	t.Run("Mirror", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; first_layer_temperature = 215, 220
M605 S3
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if Params.PrintMode != PrintModeMirror {
			t.Errorf("PrintMode: got %q, want %q", Params.PrintMode, PrintModeMirror)
		}
		if Params.Model != ModelJ1 {
			t.Errorf("Model: got %q, want %q (IDEX forces J1)", Params.Model, ModelJ1)
		}
		if Params.Version != 1 {
			t.Errorf("Version: got %d, want 1 (IDEX forces v1)", Params.Version)
		}
	})

	t.Run("Backup", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = J1
; first_layer_temperature = 215, 220
M605 S4
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if Params.PrintMode != PrintModeBackup {
			t.Errorf("PrintMode: got %q, want %q", Params.PrintMode, PrintModeBackup)
		}
	})
}

func TestParseParams_SingleExtruderUnused(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 0, 220
; first_layer_bed_temperature = -1, 60
; filament_type = PLA,ABS
; filament used [mm] = 0, 3000
; nozzle_diameter = 0.4, 0.4
; retract_length = 1.0, 1.5
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	p := Params
	if p.LeftExtruderUsed {
		t.Error("LeftExtruderUsed: got true, want false")
	}
	if !p.RightExtruderUsed {
		t.Error("RightExtruderUsed: got false, want true")
	}
	if p.ToolHead != ToolheadSingle {
		t.Errorf("ToolHead: got %q, want %q", p.ToolHead, ToolheadSingle)
	}
	if p.FilamentTypes[0] != "-" {
		t.Errorf("FilamentTypes[0]: got %q, want %q", p.FilamentTypes[0], "-")
	}
	if p.NozzleTemperatures[0] != 0 {
		t.Errorf("NozzleTemperatures[0]: got %f, want 0 (unused extruder reset)", p.NozzleTemperatures[0])
	}
	if p.Retractions[0] != 0 {
		t.Errorf("Retractions[0]: got %f, want 0 (unused extruder reset)", p.Retractions[0])
	}
}

func TestParseParams_DualFromPrinterNotes(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; filament used [mm] = 5000, 0
; printer_notes = SNAPMAKER_A350_DUAL
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if Params.ToolHead != ToolheadDual {
		t.Errorf("ToolHead: got %q, want %q (_DUAL in notes)", Params.ToolHead, ToolheadDual)
	}
}

func TestParseParams_DualFromModelName(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350 Dual
; first_layer_temperature = 215, 220
; filament used [mm] = 5000, 0
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if Params.ToolHead != ToolheadDual {
		t.Errorf("ToolHead: got %q, want %q (Dual in model name)", Params.ToolHead, ToolheadDual)
	}
}

func TestParseParams_VersionFromPrinterNotes(t *testing.T) {
	t.Run("V1 override", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; printer_notes = SNAPMAKER_GCODE_V1 config
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if Params.Version != 1 {
			t.Errorf("Version: got %d, want 1", Params.Version)
		}
	})

	t.Run("V0 override", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; printer_notes = SNAPMAKER_GCODE_V0 config
; SNAPMAKER_GCODE_V1
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if Params.Version != 0 {
			t.Errorf("Version: got %d, want 0 (notes V0 overrides header V1)", Params.Version)
		}
	})
}

func TestParseParams_SNAPMAKER_GCODE_V1_Header(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; SNAPMAKER_GCODE_V1
; printer_model = A350
; first_layer_temperature = 215, 220
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if Params.Version != 1 {
		t.Errorf("Version: got %d, want 1", Params.Version)
	}
}

func TestParseParams_RetractionFallback(t *testing.T) {
	t.Run("filament_retract_length overrides retract_length", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; filament used [mm] = 5000, 3000
; retract_length = 0.5, 0.6
; filament_retract_length = 1.0, 1.2
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if Params.Retractions[0] != 1.0 || Params.Retractions[1] != 1.2 {
			t.Errorf("Retractions: got %v, want [1.0, 1.2]", Params.Retractions)
		}
	})

	t.Run("retract_length used when no filament_retract_length", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; filament used [mm] = 5000, 3000
; retract_length = 0.8, 0.9
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if Params.Retractions[0] != 0.8 || Params.Retractions[1] != 0.9 {
			t.Errorf("Retractions: got %v, want [0.8, 0.9]", Params.Retractions)
		}
	})
}

func TestParseParams_Thumbnail(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; thumbnail begin 220x124 100
; AAAA
; BBBB
; thumbnail end
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(Params.Thumbnail) == 0 {
		t.Error("Thumbnail: expected non-empty thumbnail data")
	}
	expected := "data:image/png;base64,AAAABBBB"
	if string(Params.Thumbnail) != expected {
		t.Errorf("Thumbnail: got %q, want %q", string(Params.Thumbnail), expected)
	}
}

func TestParseParams_TotalLinesReset(t *testing.T) {
	gcode := `G0 X0
G0 X1
G0 X2
; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if Params.TotalLines < 20 {
		t.Errorf("TotalLines: got %d, want >= 20 (should reset at '; generated by')", Params.TotalLines)
	}
}

func TestParseParams_EffectiveTemperatures(t *testing.T) {
	t.Run("T0 takes priority", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; first_layer_bed_temperature = 60, 65
; filament used [mm] = 5000, 3000
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got := Params.EffectiveNozzleTemperature(); got != 215 {
			t.Errorf("EffectiveNozzleTemperature: got %f, want 215", got)
		}
		if got := Params.EffectiveBedTemperature(); got != 60 {
			t.Errorf("EffectiveBedTemperature: got %f, want 60", got)
		}
	})

	t.Run("falls back to T1 when T0 < 1", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 0, 220
; first_layer_bed_temperature = 0, 65
; filament used [mm] = 0, 3000
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got := Params.EffectiveNozzleTemperature(); got != 220 {
			t.Errorf("EffectiveNozzleTemperature: got %f, want 220 (fallback to T1)", got)
		}
		if got := Params.EffectiveBedTemperature(); got != 65 {
			t.Errorf("EffectiveBedTemperature: got %f, want 65 (fallback to T1)", got)
		}
	})
}

func TestParseParams_AllFilamentUsed(t *testing.T) {
	t.Run("both extruders used", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; filament used [mm] = 5000, 3000
; filament used [g] = 12.5, 7.5
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got := Params.AllFilamentUsed(); got != 8000 {
			t.Errorf("AllFilamentUsed: got %f, want 8000", got)
		}
		if got := Params.AllFilamentUsedWeight(); got != 20 {
			t.Errorf("AllFilamentUsedWeight: got %f, want 20", got)
		}
	})

	t.Run("one extruder unused", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 0, 220
; filament used [mm] = 0, 3000
; filament used [g] = 0, 7.5
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got := Params.AllFilamentUsed(); got != 3000 {
			t.Errorf("AllFilamentUsed: got %f, want 3000", got)
		}
		if got := Params.AllFilamentUsedWeight(); got != 7.5 {
			t.Errorf("AllFilamentUsedWeight: got %f, want 7.5", got)
		}
	})

	t.Run("both extruders unused", func(t *testing.T) {
		gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; filament used [mm] = 0, 0
; filament used [g] = 0, 0
` + _padToLines(25)

		gcodes := _parseGcodes(gcode)
		if err := ParseParams(gcodes); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if got := Params.AllFilamentUsed(); got != 0 {
			t.Errorf("AllFilamentUsed: got %f, want 0", got)
		}
		if got := Params.AllFilamentUsedWeight(); got != 0 {
			t.Errorf("AllFilamentUsedWeight: got %f, want 0", got)
		}
	})
}

func BenchmarkParseGcodeBlock(b *testing.B) {
	code := " G0.1  X1.23 Z.3 E-.004 R Y .333 F500000 ;  comment"
	b.SetBytes(int64(len(code)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		g, err := ParseGcodeBlock(code)
		if err != nil {
			b.Fatal(err)
		}
		_ = g.String()
	}
}

func BenchmarkGcodeAsType(b *testing.B) {
	g, err := ParseGcode("E-.004")
	if err != nil {
		b.Fatal(err)
	}
	var t float32
	for i := 0; i < b.N; i++ {
		err = g.AddrAs(&t)
		if err != nil {
			b.Fatal(err)
		}
		_ = t
	}
}

func BenchmarkToolNum(b *testing.B) {
	g, err := ParseGcodeBlock("M104 S255 T1 ; tool T2")
	if err != nil {
		b.Fatal(err)
	}
	for i := 0; i < b.N; i++ {
		if t, err := g.GetToolNum(); err == nil {
			if t != 1 {
				b.Fatalf("got %d, want %d", t, 1)
			}
		} else {
			b.Fatal(err)
		}
	}
}
