package fix

import (
	"os"
	"reflect"
	"strconv"
	"strings"
	"testing"
)

// headerValue extracts the value of a ";Key: value" header line.
func headerValue(t *testing.T, headers [][]byte, key string) string {
	t.Helper()
	prefix := ";" + key
	for _, h := range headers {
		line := string(h)
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimLeft(line[len(prefix):], ": "))
		}
	}
	t.Fatalf("header %q not found in %d lines", key, len(headers))
	return ""
}

// gcode that only uses T0 but slicer still emits dual values:
// the second value must be preserved (not clobbered by the first).
func TestReplaceToolNum_SingleToolCommentNotClobbered(t *testing.T) {
	gcodes := _parseGcodes(`
T0
; filament used [mm] = 1234.56, 0.00
; filament used [g] = 15.20, 0.00
	`)
	want := _parseGcodes(`
T0
; filament used [mm] = 1234.56,0.00
; filament used [g] = 15.20,0.00
	`)

	got := GcodeReplaceToolNum(gcodes)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %v, want %v", got[1].Comment(), want[1].Comment())
	}
}

// a single-value comment with only T1 seen must not panic and must be
// kept intact (previously the rewrite was silently skipped by a recover).
func TestReplaceToolNum_T1OnlySingleValue(t *testing.T) {
	raw := "T1\n; filament used [mm] = 999.99\n"
	got := GcodeReplaceToolNum(_parseGcodes(raw))
	if got[1].Comment() != "; filament used [mm] = 999.99" {
		t.Errorf("unexpected comment: %q", got[1].Comment())
	}
}

// T2-only (even tool) remaps to T0: slot 0 takes the T2 value, slot 1
// stays "0" so ParseParams still sees the right extruder as unused.
func TestReplaceToolNum_T2OnlyThreeValues(t *testing.T) {
	got := GcodeReplaceToolNum(_parseGcodes(`
T2
; filament used [mm] = 0.00, 0.00, 5000.00
; filament_type = PLA, ABS, PETG
	`))
	if got[1].Comment() != "; filament used [mm] = 5000.00,0.00" {
		t.Errorf("filament used: %q", got[1].Comment())
	}
	if got[2].Comment() != "; filament_type = PETG,ABS" {
		t.Errorf("filament_type: %q", got[2].Comment())
	}
}

func TestCopy_CommentOnlyBlock(t *testing.T) {
	cb, err := ParseGcodeBlock("; just a comment")
	if err != nil {
		t.Fatal(err)
	}
	cp := cb.Copy()
	s := cp.String()
	if strings.ContainsRune(s, 0) {
		t.Errorf("copy of comment block contains NUL byte: %q", s)
	}
	if s != "; just a comment" {
		t.Errorf("unexpected string: %q", s)
	}
	if !cp.IsComment() {
		t.Errorf("copy should still be a comment block: %q", s)
	}
}

func TestRemoveParam(t *testing.T) {
	g, err := ParseGcodeBlock("G1 X1 Y2 X3 E5")
	if err != nil {
		t.Fatal(err)
	}
	g.RemoveParam('X')
	if got := g.String(); got != "G1 Y2 E5" {
		t.Errorf("got %q, want %q", got, "G1 Y2 E5")
	}
	g.RemoveParam('Q') // no-op
	if got := g.String(); got != "G1 Y2 E5" {
		t.Errorf("got %q, want %q", got, "G1 Y2 E5")
	}
	// comment-only block must not panic
	c, _ := ParseGcodeBlock("; comment")
	c.RemoveParam('X')
	if got := c.String(); got != "; comment" {
		t.Errorf("got %q, want %q", got, "; comment")
	}
}

// file_total_lines / Lines must match the number of lines actually
// emitted (header entries + blank line after Header End + gcode lines),
// including the extra thumbnail line.
func TestHeaderLineCount(t *testing.T) {
	input := func(withThumbnail bool) string {
		s := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
; filament used [mm] = 5000, 3000
; filament used [g] = 12.5, 7.5
`
		if withThumbnail {
			s += "; thumbnail begin 220x124 100\n; AAAA\n; thumbnail end\n"
		}
		return s + _padToLines(30)
	}

	for _, tc := range []struct {
		version   int
		withThumb bool
		lineKey   string
	}{
		{0, false, "file_total_lines"},
		{0, true, "file_total_lines"},
		{1, false, "Lines"},
		{1, true, "Lines"},
	} {
		name := "v" + strconv.Itoa(tc.version)
		if tc.withThumb {
			name += "-thumb"
		}
		t.Run(name, func(t *testing.T) {
			g := input(tc.withThumb)
			if tc.version == 1 {
				// force V1 via J1
				g = strings.Replace(g, "A350", "J1", 1)
			}
			gcodes := _parseGcodes(g)
			if err := ParseParams(gcodes); err != nil {
				t.Fatal(err)
			}
			headers := headerV0()
			if tc.version == 1 {
				headers = headerV1()
			}

			want := Params.TotalLines + len(headers) + 1
			got, err := strconv.Atoi(headerValue(t, headers, tc.lineKey))
			if err != nil {
				t.Fatal(err)
			}
			if got != want {
				t.Errorf("%s = %d, want %d (TotalLines=%d, header entries=%d)",
					tc.lineKey, got, want, Params.TotalLines, len(headers))
			}
		})
	}

	// thumbnail variant: header grows by exactly the thumbnail line,
	// body grows by its own comment lines
	gcodes := _parseGcodes(input(false))
	if err := ParseParams(gcodes); err != nil {
		t.Fatal(err)
	}
	tlWithout, without := Params.TotalLines, headerValue(t, headerV0(), "file_total_lines")

	gcodes = _parseGcodes(input(true))
	if err := ParseParams(gcodes); err != nil {
		t.Fatal(err)
	}
	tlWith, with := Params.TotalLines, headerValue(t, headerV0(), "file_total_lines")

	w, _ := strconv.Atoi(without)
	c, _ := strconv.Atoi(with)
	if c-w != (tlWith-tlWithout)+1 {
		t.Errorf("thumbnail should add exactly 1 header line: with=%d without=%d (TotalLines %d -> %d)",
			c, w, tlWithout, tlWith)
	}
}

// missing filament/bed stats must not leak negative defaults into headers.
// u1Fixture resembles a Snapmaker Orca slice for the 4-toolhead U1:
// tool numbers T0-T3 appear in start gcode, temperature and fan
// commands, and the slicer stats carry 4 values.
func u1Fixture() string {
	return `; generated by Snapmaker Orca 2.2.4 on 2026-01-01
; printer_model = Snapmaker U1
; first_layer_temperature = 220, 220, 220, 220
; filament_type = PLA;PETG;ABS;ASA
; filament used [mm] = 100.00, 200.00, 300.00, 400.00
M104 S0 T0 A0
M104 S0 T1 A0
M104 S0 T2 A0
M104 S0 T3 A0
M106 P2 S0
M109 S220 T3
T0
T3
G1 X1 Y1 E0.001 F1500
` + _padToLines(10)
}

func TestIsU1Model(t *testing.T) {
	if !IsU1Model(_parseGcodes(u1Fixture())) {
		t.Error("U1 fixture not detected")
	}
	neg := strings.Replace(u1Fixture(), "Snapmaker U1", "Snapmaker A350", 1)
	if IsU1Model(_parseGcodes(neg)) {
		t.Error("A350 file falsely detected as U1")
	}
	neg2 := strings.Replace(u1Fixture(), "; printer_model = Snapmaker U1\n", "", 1)
	if IsU1Model(_parseGcodes(neg2)) {
		t.Error("file without printer_model falsely detected as U1")
	}
}

// detection must hold on real slices from both slicers
func TestIsU1Model_RealFiles(t *testing.T) {
	for _, name := range []string{
		"testdata/u1_snapmaker_orca.gcode",
		"testdata/u1_orcaslicer.gcode",
	} {
		raw, err := os.ReadFile(name)
		if err != nil {
			t.Fatal(err)
		}
		if !IsU1Model(_parseGcodes(string(raw))) {
			t.Errorf("%s: real U1 slice not detected", name)
		}
	}
}

func TestGcodeReplaceToolNum_U1Passthrough(t *testing.T) {
	gcodes := _parseGcodes(u1Fixture())
	want := make([]string, 0, len(gcodes))
	for _, g := range gcodes {
		want = append(want, g.String())
	}

	got := GcodeReplaceToolNum(gcodes)
	if len(got) != len(gcodes) {
		t.Fatalf("length changed: %d -> %d", len(gcodes), len(got))
	}
	for i := range got {
		if s := got[i].String(); s != want[i] {
			t.Fatalf("line %d modified: %q -> %q", i, want[i], s)
		}
	}
}

func TestHeaderNoNegativeDefaults(t *testing.T) {
	gcode := `; generated by PrusaSlicer 2.7.0
; printer_model = A350
; first_layer_temperature = 215, 220
` + _padToLines(25)

	gcodes := _parseGcodes(gcode)
	if err := ParseParams(gcodes); err != nil {
		t.Fatal(err)
	}
	for _, h := range headerV0() {
		line := string(h)
		for _, key := range []string{"matierial_weight", "matierial_length", "build_plate_temperature"} {
			if strings.HasPrefix(line, ";"+key+":") {
				v, err := strconv.ParseFloat(strings.TrimSpace(line[len(key)+2:]), 64)
				if err == nil && v < 0 {
					t.Errorf("%s is negative: %q", key, line)
				}
			}
		}
	}
	if got := headerValue(t, headerV1(), "Bed Temperature"); strings.HasPrefix(got, "-") {
		t.Errorf("V1 Bed Temperature is negative: %q", got)
	}
}
